---
version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Ry26oNzEF4d7Mx
      - MYSQL_DATABASE=orion

  server:
    restart: always
    build:
      context: orion-server
      args:
        sha: 3cbbdbe24706226cf7d218cc5f6ce81a399e7abe
        database_host: db
        database_port: 3306
        database_name: orion
        database_user: root
        database_password: Ry26oNzEF4d7Mx
    depends_on:
      - db

  web:
    restart: always
    build:
      context: orion-web
      args:
        sha: 8c18dce19a2199c4c53e1145881d362a05018cd5
        mapbox_api_token: ${MAPBOX_API_TOKEN}
    depends_on:
      - server

  http:
    image: nginx:1.13.7
    restart: always
    volumes:
      - ./http/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${PORT}:80"
    depends_on:
      - web
